### ISSUE TITLE
Book keys shifted

### ISSUE THREAD

**Issue by mansouryaacoubi** [sunnah-com/api#99]
Assalamu alaikum wa rahmatu Allahi wa barakatu,

I just wanted to mention that the first book of _Riyad as-Salihin_ has two different keys depending from where you are reading.
On my smartphone the first book starts with the key 1 and on the website it starts with 0.
Therefore all the book keys on the phone are shifted by one.

E.g. _The Book of the Remembrance of Allah_ on the website is the 15th book and in the app it's the 16th book.
As far as I know both the website and the app use the Sunnah.com-API so the book numbers should always be the same but that's not the case.

Barakallahu Feekum
Wa alaikum assalam

![image](https://user-images.githubusercontent.com/6348858/93438979-469f0700-f8ce-11ea-981a-6a95bc5be21b.png)  
![image](https://user-images.githubusercontent.com/6348858/93438963-430b8000-f8ce-11ea-855f-edb62f3412f6.png)

**Comment by ahadith** [comment]
Wa`alaykum ussalam warahmatullahi wabarakatuh

Jazakallahu khair. Which app is this?

We currently don't have an officially supported app yet, and we recently made the change in Riyad as-Salihin to concord with well-known printed editions. Whoever made the app has probably not refreshed their data.

Closing the issue since we can't update someone else's app.
